import http from 'node:http';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { SQSClient, GetQueueAttributesCommand, SendMessageCommand } from '@aws-sdk/client-sqs';
import { scoreLead, matchProducts, fallbackMessage, verifyWebsite, isSuppressed, audit, uuid, openaiResponses, checkOpenAI, checkHunter, checkSES, checkS3, sendSESEmail, normalizePhone, classifyInternetPresence } from './services.mjs';
import { routeSms, smsOpener, smsEligibility, sendTwilioSms, sendTermiiSms } from './sms.mjs';
import { createRepository } from '../db/repository.mjs';
import { verifySnsMessage, confirmSnsSubscription, parseSesNotification } from './sns.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');
const leadsPath = path.join(repoRoot, 'data', 'leads.json');
const port = Number(process.env.PORT || 8787);
const sessions = new Map();
const events = [];
const suppressions = [];
const queue = [];
const revenue = [];
const campaign = { id: 'campaign-001', name: 'CAP V0.1 — Campaign 001 — Website Opportunity', objective: 'Acquisition and controlled email outreach', status: 'ACTIVE', daily_limit: Number(process.env.CAP_DAILY_EMAIL_OUTREACH_LIMIT || 250), approval_required: true, sender: process.env.SES_FROM_EMAIL || '' };
const now = () => new Date().toISOString();
const sqsClient = new SQSClient({ region: process.env.AWS_REGION || 'eu-north-1' });
async function enqueueProduction(job) { if (repository) await repository.enqueue(job); if (process.env.CAP_SQS_QUEUE_URL) { const input = { QueueUrl: process.env.CAP_SQS_QUEUE_URL, MessageBody: JSON.stringify(job) }; if (process.env.CAP_SQS_QUEUE_URL.endsWith('.fifo')) { input.MessageDeduplicationId = job.idempotency_key; input.MessageGroupId = 'cap-email'; } await sqsClient.send(new SendMessageCommand(input)); } }
function rawLeads() { try { return JSON.parse(fs.readFileSync(leadsPath, 'utf8')); } catch { return []; } }
function normalizeLead(lead) { const internetPresence = classifyInternetPresence(lead); const productFits = lead.product_fits || matchProducts(lead); const highIntent = Boolean(lead.high_intent || lead.request_type || /request|rfi|redesign/i.test(String(lead.stage || ''))); return { ...lead, uid: String(lead.uid || lead.id), lifecycle_stage: lead.lifecycle_stage || (highIntent ? 'HIGH_INTENT' : 'IMPORTED'), website_status: lead.websiteStatus || lead.website_status || 'UNKNOWN', internet_presence: internetPresence, approval_state: lead.approval_state || (highIntent ? 'PENDING' : 'PENDING'), sms_approval_state: lead.sms_approval_state || 'PENDING', consent_status: lead.consent_status || 'UNKNOWN', sms_route: routeSms(lead.phone), sms_message: lead.sms_message || smsOpener(lead, productFits[0]?.product), sms_status: lead.sms_status || 'PREPARED', suppressed: Boolean(lead.suppressed), high_intent: highIntent, score: lead.score && typeof lead.score === 'object' ? lead.score : scoreLead(lead), product_fits: productFits, audit: lead.audit || [] }; }
let leads = rawLeads().map(normalizeLead);
const repository = createRepository();
const repositoryReady = repository ? repository.bootstrap({ records: leads.map((lead) => ({ lead_id: lead.uid, business: lead.name, ...lead })) }, campaign.name).then(async (result) => { const persisted = await repository.listLeads(); if (persisted.length) leads = persisted.map(normalizeLead); console.log('DATABASE_BOOTSTRAPPED', JSON.stringify({ imported: result.imported, duplicates_reconciled: result.duplicates_reconciled })); }).catch((error) => console.error('DATABASE_INIT_FAILED', error.message)) : Promise.resolve();

function json(res, status, payload) { res.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store' }); res.end(JSON.stringify(payload)); }
function parseCookies(req) { return Object.fromEntries((req.headers.cookie || '').split(';').filter(Boolean).map((p) => { const [k, ...v] = p.trim().split('='); return [k, decodeURIComponent(v.join('='))]; })); }
function auth(req) { const token = parseCookies(req).cap_session; return token && sessions.get(token); }
function requireAuth(req, res) { const user = auth(req); if (!user) { json(res, 401, { error: 'unauthorized', message: 'Login required' }); return null; } return user; }
async function body(req) { let raw = ''; for await (const chunk of req) raw += chunk; if (!raw) return {}; try { return JSON.parse(raw); } catch { return {}; } }
async function formBody(req) { let raw = ''; for await (const chunk of req) raw += chunk; return Object.fromEntries(new URLSearchParams(raw)); }
function findLead(id) { return leads.find((l) => l.uid === String(id) || String(l.id) === String(id)); }
function notFound(res) { return json(res, 404, { error: 'not_found' }); }
async function persistLead(lead) { if (repository) await repository.saveLead(lead); }
async function dailyEmailCount() { if (repository) { const result = await repository.pool.query("SELECT count(*)::int AS count FROM cap_outreach_ledger WHERE date_bucket=current_date AND channel='EMAIL' AND final_state IN ('RESERVED','QUEUED','ACCEPTED','DELIVERED')"); return result.rows[0].count; } const day = new Date().toISOString().slice(0, 10); return leads.filter((l) => l.email_sent_at?.slice(0, 10) === day || l.email_status === 'ACCEPTED' && l.email_sent_date === day).length; }
async function dashboard() { const emailOutreachToday = await dailyEmailCount(); const count = (fn) => leads.filter(fn).length; const today = new Date().toISOString().slice(0, 10); return { total_unique_prospects: leads.length, imported: leads.length, acquired_today: count((l) => (l.acquisition_date || '').slice(0, 10) === today), acquisition_target: Number(process.env.CAP_DAILY_ACQUISITION_TARGET || 1000), duplicates_rejected_today: count((l) => (l.reconciled_at || '').slice(0, 10) === today && l.reconciliation_status === 'DUPLICATE'), enriched_today: count((l) => (l.enriched_at || '').slice(0, 10) === today), hunter_enriched: count((l) => l.hunter_enrichment), hunter_verified: count((l) => l.email_verification?.source === 'hunter' && l.email_verification.status === 'valid'), openai_qualified: count((l) => l.openai_qualification), email_eligible: count((l) => l.email_eligibility === 'ELIGIBLE'), email_outreach_today: emailOutreachToday, email_outreach_limit: Number(process.env.CAP_DAILY_EMAIL_OUTREACH_LIMIT || 250), verified: count((l) => l.website_status === 'ACTIVE'), enriched: count((l) => Boolean(l.email)), qualified: count((l) => l.score?.total >= 60), awaiting_approval: count((l) => l.approval_state === 'PENDING'), approved: count((l) => l.approval_state === 'APPROVED'), high_intent: count((l) => l.high_intent), queued: queue.filter((j) => j.status === 'QUEUED').length, sent: count((l) => l.email_status === 'SENT' || l.lifecycle_stage === 'SENT'), delivered: count((l) => l.email_delivery_state === 'DELIVERED' || l.lifecycle_stage === 'DELIVERED'), bounced: count((l) => l.email_delivery_state === 'BOUNCED' || l.lifecycle_stage === 'BOUNCED'), complaints: count((l) => l.email_complaint_state === 'COMPLAINT'), replies: count((l) => l.response), positive_replies: count((l) => l.response?.classification === 'POSITIVE'), opportunities: count((l) => l.opportunity), proposals: count((l) => l.opportunity?.stage === 'PROPOSAL'), pipeline_value: revenue.reduce((s, r) => s + Number(r.expected_value || 0), 0), won_revenue: revenue.filter((r) => r.status === 'WON').reduce((s, r) => s + Number(r.amount || 0), 0), send_enabled: process.env.CAP_EMAIL_SEND_ENABLED === 'true', sms_send_enabled: process.env.CAP_SMS_SEND_ENABLED === 'true' }; }
async function queueEmail(lead, user) { const limit = Number(process.env.CAP_DAILY_EMAIL_OUTREACH_LIMIT || 250); if (!repository) throw new Error('postgres_required_for_email_reservation'); if (await repository.isSuppressed(lead)) { lead.suppressed = true; await persistLead(lead); throw new Error('suppressed'); } if (!lead.email || lead.suppressed || lead.email_verification?.status !== 'valid') throw new Error('verified_email_required'); if (lead.high_intent) throw new Error('high_intent_requires_human_follow_up'); if (lead.email_status === 'QUEUED' || lead.email_status === 'SENT') throw new Error('email_already_queued_or_sent'); const idempotency_key = `email:${lead.uid}:${campaign.id}:${new Date().toISOString().slice(0, 10)}`; await repository.reserveEmail({ leadId: lead.uid, campaignId: campaign.id, idempotencyKey: idempotency_key, dailyLimit: limit }); const job = { id: uuid(), idempotency_key, type: 'EMAIL_SEND', lead_id: lead.uid, provider: 'aws-ses', to: lead.email, subject: lead.message?.subject || fallbackMessage(lead, lead.product_fits[0]).subject, body: lead.message?.body || fallbackMessage(lead, lead.product_fits[0]).body, status: 'QUEUED', attempts: 0, campaign_id: campaign.id, created_at: now(), actor: user.email }; queue.push(job); await enqueueProduction(job); lead.email_status = 'QUEUED'; lead.lifecycle_stage = 'EMAIL_QUEUED'; await persistLead(lead); return job; }
async function readiness() { const results = await Promise.all([checkOpenAI(), checkHunter(), checkSES(), checkS3(), repository ? repository.health().then(() => ({ status: 'READY', reason: 'PostgreSQL query succeeded' })).catch((e) => ({ status: 'BLOCKED', reason: e.message })) : Promise.resolve({ status: 'BLOCKED', reason: 'DATABASE_URL not configured' }), (async () => { try { if (!process.env.CAP_SQS_QUEUE_URL) throw new Error('queue_url_not_configured'); await new SQSClient({ region: process.env.AWS_REGION || 'eu-north-1' }).send(new GetQueueAttributesCommand({ QueueUrl: process.env.CAP_SQS_QUEUE_URL, AttributeNames: ['ApproximateNumberOfMessages'] })); return { status: 'READY', reason: 'SQS queue attributes read succeeded' }; } catch (e) { return { status: 'BLOCKED', reason: e.message.slice(0, 180) }; } })(), (async () => { try { if (!process.env.TWILIO_ACCOUNT_SID || !process.env.TWILIO_AUTH_TOKEN) throw new Error('twilio_credentials_not_configured'); const authHeader = Buffer.from(`${process.env.TWILIO_ACCOUNT_SID}:${process.env.TWILIO_AUTH_TOKEN}`).toString('base64'); const r = await fetch(`https://api.twilio.com/2010-04-01/Accounts/${process.env.TWILIO_ACCOUNT_SID}.json`, { headers: { Authorization: `Basic ${authHeader}` }, signal: AbortSignal.timeout(8000) }); if (!r.ok) throw new Error(`twilio_http_${r.status}`); return { status: 'READY', reason: 'Twilio authenticated account request succeeded' }; } catch (e) { return { status: 'DEGRADED', reason: e.message.slice(0, 180) }; } })()]); const [openai, hunter, ses, s3, rds, sqs, twilio] = results; return { OPENAI: openai, HUNTER: hunter, SES: ses, S3: s3, RDS: rds, SQS: sqs, TWILIO: twilio, WEBSITE_VERIFIER: { status: 'READY', reason: 'HTTP/DNS verifier available' }, send_gates: { email: process.env.CAP_EMAIL_SEND_ENABLED === 'true', sms: process.env.CAP_SMS_SEND_ENABLED === 'true' } }; }

function validTwilioWebhook(req, params) { const token = process.env.TWILIO_AUTH_TOKEN; if (!token) return false; const signature = req.headers['x-twilio-signature']; if (!signature) return false; const url = `${process.env.PUBLIC_API_BASE_URL || `http://${req.headers.host}`}${req.url}`; const expected = crypto.createHmac('sha1', token).update(url + Object.keys(params).sort().map((key) => `${key}${params[key]}`).join('')).digest('base64'); return crypto.timingSafeEqual(Buffer.from(String(signature)), Buffer.from(expected)); }

const server = http.createServer(async (req, res) => {
  await repositoryReady;
  const url = new URL(req.url, `http://${req.headers.host || 'localhost'}`);
  const allowedOrigin = process.env.FRONTEND_ORIGIN || `http://${req.headers.host || 'localhost'}`;
  res.setHeader('Access-Control-Allow-Origin', allowedOrigin); res.setHeader('Vary', 'Origin'); res.setHeader('Access-Control-Allow-Credentials', 'true');
  if (req.method === 'OPTIONS') { res.writeHead(204, { 'Access-Control-Allow-Headers': 'Content-Type, Cookie, X-Requested-With' }); return res.end(); }
  if (url.pathname === '/health' && req.method === 'GET') return json(res, 200, { ok: true, service: 'aureum-cap-v0-1', region: process.env.AWS_REGION || 'eu-north-1', database_authoritative: Boolean(repository), acquisition_target: Number(process.env.CAP_DAILY_ACQUISITION_TARGET || 1000), email_limit: Number(process.env.CAP_DAILY_EMAIL_OUTREACH_LIMIT || 250) });
  if (url.pathname === '/readiness' && req.method === 'GET') { const detail = await readiness(); const blocked = Object.entries(detail).filter(([k, v]) => !['send_gates'].includes(k) && v.status !== 'READY').map(([k, v]) => `${k}:${v.status}`); return json(res, blocked.length ? 503 : 200, { status: blocked.length ? 'DEGRADED' : 'READY', ready: !blocked.length, blocked, providers: detail }); }
  if (url.pathname === '/api/v1/auth/login' && req.method === 'POST') { const b = await body(req); if (!process.env.CAP_ADMIN_EMAIL || !process.env.CAP_ADMIN_PASSWORD) return json(res, 503, { error: 'auth_not_configured' }); if (String(b.email) !== process.env.CAP_ADMIN_EMAIL || b.password !== process.env.CAP_ADMIN_PASSWORD) return json(res, 401, { error: 'invalid_credentials' }); const token = uuid(); const user = { id: 'operator-1', email: String(b.email), role: 'admin', name: 'Aureum CAP Operator' }; sessions.set(token, user); res.setHeader('Set-Cookie', `cap_session=${encodeURIComponent(token)}; HttpOnly; SameSite=None; Secure; Path=/`); return json(res, 200, { user }); }
  if (url.pathname === '/api/v1/auth/me' && req.method === 'GET') { const user = auth(req); return user ? json(res, 200, { user }) : json(res, 401, { error: 'unauthorized' }); }
  if (url.pathname === '/api/v1/auth/logout' && req.method === 'POST') { sessions.delete(parseCookies(req).cap_session); res.setHeader('Set-Cookie', 'cap_session=; Max-Age=0; HttpOnly; SameSite=Lax; Path=/'); return json(res, 200, { ok: true }); }
  if (url.pathname === '/api/v1/pilot/summary' && req.method === 'GET') return json(res, 200, { campaign: campaign.name, ...(await dashboard()) });
  if (url.pathname === '/api/v1/webhooks/ses' && req.method === 'POST') { let payload; try { payload = await body(req); const message = await verifySnsMessage(payload, { topicArn: process.env.CAP_SES_SNS_TOPIC_ARN }); if (message.Type === 'SubscriptionConfirmation') { await confirmSnsSubscription(message, process.env.CAP_SES_SNS_TOPIC_ARN); return json(res, 200, { ok: true, subscription_confirmed: true }); } if (message.Type !== 'Notification') return json(res, 200, { ok: true, ignored: true }); const sesEvent = parseSesNotification(message); const destination = sesEvent.mail.destination || []; const lead = leads.find((l) => l.email && destination.includes(l.email)); if (lead) { lead.email_delivery_state = sesEvent.event === 'Delivery' ? 'DELIVERED' : sesEvent.event === 'Bounce' ? 'BOUNCED' : sesEvent.event === 'Complaint' ? 'COMPLAINT' : lead.email_delivery_state; if (['Bounce', 'Complaint'].includes(sesEvent.event)) { lead.suppressed = true; if (repository && lead.email) await repository.recordSuppression('email', lead.email, sesEvent.event.toLowerCase(), 'ses-sns'); } await persistLead(lead); } if (repository) await repository.saveEvent({ type: `ses.${sesEvent.event.toLowerCase()}`, entity_type: 'lead', entity_id: lead?.uid, payload: sesEvent.payload }); return json(res, 200, { ok: true, event: sesEvent.event }); } catch (error) { return json(res, 403, { error: 'invalid_sns_notification', message: error.message }); } }
  if (url.pathname.startsWith('/api/v1/webhooks/sms/') && req.method === 'POST') { const params = await formBody(req); if (!validTwilioWebhook(req, params)) return json(res, 403, { error: 'invalid_twilio_signature' }); const lead = leads.find((item) => item.sms_provider_id === params.MessageSid || item.phone === params.From); const text = String(params.Body || '').trim(); if (lead && url.pathname.endsWith('/inbound')) { lead.response = { classification: /^(stop|unsubscribe|cancel|quit|end|revoke)$/i.test(text) ? 'OPT_OUT' : 'RECEIVED', body: text, received_at: now() }; lead.lifecycle_stage = 'REPLIED'; if (lead.response.classification === 'OPT_OUT') { lead.suppressed = true; suppressions.push({ phone: normalizePhone(lead.phone), reason: 'recipient_opt_out', source: 'twilio', created_at: now() }); if (repository) await repository.recordSuppression('phone', normalizePhone(lead.phone), 'recipient_opt_out', 'twilio'); } await persistLead(lead); } if (lead && url.pathname.endsWith('/status')) { lead.sms_status = params.MessageStatus || lead.sms_status; lead.lifecycle_stage = params.MessageStatus === 'delivered' ? 'DELIVERED' : ['undelivered', 'failed'].includes(params.MessageStatus) ? 'BOUNCED' : lead.lifecycle_stage; await persistLead(lead); } return res.end('<Response></Response>'); }
  const user = requireAuth(req, res); if (!user) return;
  if (url.pathname === '/api/v1/dashboard' && req.method === 'GET') return json(res, 200, await dashboard());
  if (url.pathname === '/api/v1/leads' && req.method === 'GET') { const q = (url.searchParams.get('q') || '').toLowerCase(); const status = url.searchParams.get('status'); const result = leads.filter((l) => (!q || `${l.name} ${l.category} ${l.location} ${l.email}`.toLowerCase().includes(q)) && (!status || l.lifecycle_stage === status)); return json(res, 200, { data: result, total: result.length }); }
  const leadMatch = url.pathname.match(/^\/api\/v1\/leads\/([^/]+)$/); if (leadMatch && req.method === 'GET') { const lead = findLead(leadMatch[1]); return lead ? json(res, 200, { data: lead }) : notFound(res); }
  const emailAction = url.pathname.match(/^\/api\/v1\/leads\/([^/]+)\/(queue-email|send-email|qualify)$/); if (emailAction && req.method === 'POST') { const lead = findLead(emailAction[1]); if (!lead) return notFound(res); try { if (emailAction[2] === 'qualify') { const r = await openaiResponses(`Qualify this business for website and automation services. Return concise JSON with score 0-100, high_intent boolean, rationale. Business: ${lead.name}; category: ${lead.category}; location: ${lead.location}; website: ${lead.website || 'none'}`, { name: 'qualification', schema: { type: 'object', properties: { score: { type: 'number' }, high_intent: { type: 'boolean' }, rationale: { type: 'string' } }, required: ['score', 'high_intent', 'rationale'], additionalProperties: false } }); lead.openai_qualification = { ...JSON.parse(r.output_text), model: r.model, request_id: r.id, qualified_at: now() }; lead.high_intent = lead.openai_qualification.high_intent; await persistLead(lead); return json(res, 200, { data: lead }); } if (emailAction[2] === 'queue-email') return json(res, 202, { data: await queueEmail(lead, user) }); return json(res, 409, { error: 'direct_send_disabled', message: 'Use queue-email; the SQS worker records ACCEPTED only after SES returns a MessageId.' }); } catch (e) { return json(res, 409, { error: 'email_action_failed', message: e.message }); } }
  if (leadMatch && req.method === 'PATCH') { const lead = findLead(leadMatch[1]); if (!lead) return notFound(res); Object.assign(lead, await body(req)); await persistLead(lead); audit(events, user.email, 'lead.updated', 'lead', lead.uid); return json(res, 200, { data: lead }); }
  const actionMatch = url.pathname.match(/^\/api\/v1\/leads\/([^/]+)\/(approve|reject|suppress|verify|prepare|prepare-sms|approve-sms|queue-sms|send-sms)$/); if (actionMatch && req.method === 'POST') { const lead = findLead(actionMatch[1]); if (!lead) return notFound(res); const action = actionMatch[2]; if (action === 'approve') { if (lead.suppressed || isSuppressed(lead, suppressions)) return json(res, 409, { error: 'suppressed' }); lead.approval_state = 'APPROVED'; lead.lifecycle_stage = 'APPROVED'; } if (action === 'reject') { lead.approval_state = 'REJECTED'; lead.lifecycle_stage = 'REJECTED'; } if (action === 'suppress') { lead.suppressed = true; lead.approval_state = 'REJECTED'; lead.lifecycle_stage = 'SUPPRESSED'; suppressions.push({ phone: normalizePhone(lead.phone), email: lead.email, reason: 'manual', created_at: now() }); if (repository) { if (lead.email) await repository.recordSuppression('email', lead.email, 'manual', user.email); if (lead.phone) await repository.recordSuppression('phone', normalizePhone(lead.phone), 'manual', user.email); } } if (action === 'verify') { lead.website_audit = await verifyWebsite(lead.website); lead.website_status = lead.website_audit.status; } if (action === 'prepare') { lead.message = fallbackMessage(lead, lead.product_fits[0]); lead.lifecycle_stage = 'MESSAGE_READY'; } if (action === 'prepare-sms') { lead.sms_message = smsOpener(lead, lead.product_fits[0]?.product); lead.sms_status = 'PREPARED'; } if (action === 'approve-sms') { lead.sms_approval_state = 'APPROVED'; lead.lifecycle_stage = 'SMS_APPROVED'; } if (action === 'queue-sms') { const eligibility = smsEligibility(lead); if (!eligibility.eligible) return json(res, 409, { error: 'sms_not_eligible', reason: eligibility.reason }); const job = { id: uuid(), idempotency_key: `sms:${lead.uid}:${new Date().toISOString().slice(0, 10)}`, type: 'SMS_SEND', lead_id: lead.uid, provider: eligibility.route.provider, to: eligibility.route.phone, body: lead.sms_message, status: 'QUEUED', attempts: 0, created_at: now() }; queue.push(job); await enqueueProduction(job); lead.sms_status = 'QUEUED'; } if (action === 'send-sms') { if (process.env.CAP_SMS_SEND_ENABLED !== 'true') return json(res, 409, { error: 'sms_send_disabled' }); const eligibility = smsEligibility(lead); if (!eligibility.eligible) return json(res, 409, { error: 'sms_not_eligible' }); const result = eligibility.route.provider === 'twilio' ? await sendTwilioSms({ to: eligibility.route.phone, body: lead.sms_message, statusCallback: process.env.SMS_STATUS_CALLBACK_URL }) : await sendTermiiSms({ to: eligibility.route.phone, body: lead.sms_message }); lead.sms_provider_id = result.provider_id; lead.sms_status = result.status; lead.sms_sent_at = now(); lead.lifecycle_stage = 'SENT'; } await persistLead(lead); audit(events, user.email, `lead.${action}`, 'lead', lead.uid); return json(res, 200, { data: lead }); }
  if (url.pathname === '/api/v1/approvals/bulk' && req.method === 'POST') { const b = await body(req); const ids = Array.isArray(b.ids) ? b.ids : []; const approved = []; for (const id of ids.map(String)) { const lead = findLead(id); if (lead && !lead.suppressed) { lead.approval_state = 'APPROVED'; lead.lifecycle_stage = 'APPROVED'; approved.push(lead.uid); await persistLead(lead); } } return json(res, 200, { approved }); }
  if (url.pathname === '/api/v1/queue' && req.method === 'GET') return json(res, 200, { data: repository ? await repository.listQueue() : queue });
  if (url.pathname === '/api/v1/events' && req.method === 'GET') return json(res, 200, { data: events });
  if (url.pathname === '/api/v1/revenue' && req.method === 'GET') return json(res, 200, { data: revenue, totals: await dashboard() });
  return notFound(res);
});
server.listen(port, '0.0.0.0', () => console.log(`CAP API listening on ${port}`));
process.on('SIGTERM', () => server.close(() => process.exit(0))); process.on('SIGINT', () => server.close(() => process.exit(0)));
