import pg from 'pg';
import { randomUUID } from 'node:crypto';
import { normalizeDomain, normalizeEmail, normalizePhone, normalizeKey } from '../server/services.mjs';
const { Pool } = pg;

const strongIdentity = (record) => ({
  domain: normalizeDomain(record.website || record.domain),
  email: normalizeEmail(record.email),
  phone: normalizePhone(record.phone),
  companyLocation: `${normalizeKey(record.name || record.business)}|${normalizeKey(record.location || record.address)}`,
});
const identifiers = (record) => { const i = strongIdentity(record); return [i.domain && `domain:${i.domain}`, i.email && `email:${i.email}`, i.phone && `phone:${i.phone}`, i.companyLocation && i.companyLocation !== '|' && `company:${i.companyLocation}`].filter(Boolean); };
const highIntent = (r) => Boolean(r.high_intent || r.request_type || /rfi|request|redesign/i.test(String(r.stage || '')));

export function reconcileRecords(records = []) {
  const groups = []; const byIdentifier = new Map(); const conflicts = []; const events = [];
  for (const input of records) {
    const record = { ...input }; const ids = identifiers(record); const matches = [...new Set(ids.map((id) => byIdentifier.get(id)).filter((x) => x !== undefined))];
    if (!matches.length) { const group = { record, ids, sourceRecords: [record] }; const index = groups.push(group) - 1; for (const id of ids) byIdentifier.set(id, index); }
    else {
      const primary = groups[matches[0]];
      if (matches.some((x) => x !== matches[0])) { conflicts.push({ record, matching_groups: matches, identifiers: ids }); events.push({ type: 'CONFLICT_REQUIRES_MANUAL_REVIEW', record, groups: matches }); continue; }
      const prior = primary.record; const stronger = (record.email ? 2 : 0) + (record.website ? 1 : 0) + (record.phone ? 1 : 0) > (prior.email ? 2 : 0) + (prior.website ? 1 : 0) + (prior.phone ? 1 : 0);
      primary.record = stronger ? { ...prior, ...record } : { ...record, ...prior }; primary.sourceRecords.push(record); for (const id of ids) byIdentifier.set(id, matches[0]); events.push({ type: 'DUPLICATE_RECONCILED', duplicate: record, kept: primary.record.lead_id || primary.record.id });
    }
  }
  for (const group of groups) if (group.sourceRecords.some(highIntent)) group.record.high_intent = true;
  return { records: groups.map((g) => g.record), duplicates: records.length - groups.length - conflicts.length, conflicts, events, identifiers: [...byIdentifier.keys()] };
}

export function createRepository() {
  if (!process.env.DATABASE_URL) return null;
  const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: process.env.DATABASE_SSL === 'false' ? false : { rejectUnauthorized: false }, max: Number(process.env.DATABASE_POOL_MAX || 5) });
  const query = (text, values) => pool.query(text, values);
  return {
    pool,
    async health() { const result = await query('select 1 as ok'); return result.rows[0].ok === 1; },
    async bootstrap(manifest, campaignName) {
      await query(`CREATE EXTENSION IF NOT EXISTS pgcrypto;
        CREATE TABLE IF NOT EXISTS cap_leads (lead_id text PRIMARY KEY, business text NOT NULL, phone text, normalized_domain text, normalized_email text, normalized_phone text, company_location_key text, internet_presence text, high_intent boolean NOT NULL DEFAULT false, record jsonb NOT NULL, updated_at timestamptz NOT NULL DEFAULT now());
        ALTER TABLE cap_leads ADD COLUMN IF NOT EXISTS internet_presence text;
        CREATE TABLE IF NOT EXISTS cap_lead_identifiers (identifier text PRIMARY KEY, lead_id text NOT NULL REFERENCES cap_leads(lead_id) ON DELETE CASCADE, identifier_type text NOT NULL, verified boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
        CREATE TABLE IF NOT EXISTS cap_queue_jobs (id uuid PRIMARY KEY, lead_id text NOT NULL, type text NOT NULL, provider text, payload jsonb NOT NULL, status text NOT NULL DEFAULT 'QUEUED', attempts integer NOT NULL DEFAULT 0, available_at timestamptz NOT NULL DEFAULT now(), locked_at timestamptz, last_error text, completed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
        CREATE UNIQUE INDEX IF NOT EXISTS cap_queue_idempotency_uq ON cap_queue_jobs((payload->>'idempotency_key')) WHERE payload->>'idempotency_key' IS NOT NULL;
        CREATE INDEX IF NOT EXISTS cap_queue_jobs_status_idx ON cap_queue_jobs(status,available_at);
        CREATE TABLE IF NOT EXISTS cap_outreach_ledger (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), lead_id text NOT NULL, campaign_id text NOT NULL, channel text NOT NULL, date_bucket date NOT NULL, idempotency_key text NOT NULL UNIQUE, queued_at timestamptz NOT NULL DEFAULT now(), provider_message_id text, provider_accepted_at timestamptz, final_state text NOT NULL DEFAULT 'RESERVED', UNIQUE(lead_id,campaign_id,channel,date_bucket));
        CREATE INDEX IF NOT EXISTS cap_outreach_day_idx ON cap_outreach_ledger(date_bucket,channel);
        CREATE TABLE IF NOT EXISTS cap_suppressions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), kind text NOT NULL, value text NOT NULL, reason text NOT NULL, source text, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(kind,value));
        CREATE TABLE IF NOT EXISTS cap_acquisition_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), date_bucket date NOT NULL, source text NOT NULL, discovered integer NOT NULL DEFAULT 0, duplicates integer NOT NULL DEFAULT 0, new_unique integer NOT NULL DEFAULT 0, no_web_presence integer NOT NULL DEFAULT 0, social_only integer NOT NULL DEFAULT 0, weak_website integer NOT NULL DEFAULT 0, domain_prospects integer NOT NULL DEFAULT 0, enriched integer NOT NULL DEFAULT 0, verified_email integer NOT NULL DEFAULT 0, phone_only integer NOT NULL DEFAULT 0, rejected integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now());
        CREATE TABLE IF NOT EXISTS cap_provider_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), provider text NOT NULL, provider_event_id text, lead_id text, payload jsonb NOT NULL, received_at timestamptz NOT NULL DEFAULT now(), UNIQUE(provider,provider_event_id));
        CREATE TABLE IF NOT EXISTS cap_acquisition_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), lead_id text, event_type text NOT NULL, source text, payload jsonb NOT NULL DEFAULT '{}', occurred_at timestamptz NOT NULL DEFAULT now());
        CREATE TABLE IF NOT EXISTS cap_admin_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), actor text NOT NULL, event_type text NOT NULL, entity_type text, entity_id text, payload jsonb NOT NULL DEFAULT '{}', occurred_at timestamptz NOT NULL DEFAULT now());
        CREATE INDEX IF NOT EXISTS cap_admin_events_time_idx ON cap_admin_events(occurred_at DESC);
        CREATE INDEX IF NOT EXISTS cap_acquisition_runs_time_idx ON cap_acquisition_runs(created_at DESC);`);
      const reconciled = reconcileRecords(manifest.records || []);
      for (const record of reconciled.records) {
        const leadId = String(record.lead_id ?? record.id); const id = strongIdentity(record); const presence = record.internet_presence || record.internetPresence || (record.website ? 'WEAK_WEBSITE' : 'NO_WEB_PRESENCE');
        await query(`INSERT INTO cap_leads(lead_id,business,phone,normalized_domain,normalized_email,normalized_phone,company_location_key,internet_presence,high_intent,record) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(lead_id) DO UPDATE SET business=EXCLUDED.business,phone=COALESCE(cap_leads.phone,EXCLUDED.phone),normalized_domain=COALESCE(cap_leads.normalized_domain,EXCLUDED.normalized_domain),normalized_email=COALESCE(cap_leads.normalized_email,EXCLUDED.normalized_email),normalized_phone=COALESCE(cap_leads.normalized_phone,EXCLUDED.normalized_phone),company_location_key=COALESCE(cap_leads.company_location_key,EXCLUDED.company_location_key),internet_presence=COALESCE(EXCLUDED.internet_presence,cap_leads.internet_presence),high_intent=cap_leads.high_intent OR EXCLUDED.high_intent,record=cap_leads.record || EXCLUDED.record,updated_at=now()`, [leadId, record.business || record.name || 'Unknown', record.phone || null, id.domain || null, id.email || null, id.phone || null, id.companyLocation, presence, highIntent(record), record]);
        for (const value of identifiers(record)) { const [type, ...rest] = value.split(':'); await query('INSERT INTO cap_lead_identifiers(identifier,lead_id,identifier_type,verified) VALUES($1,$2,$3,$4) ON CONFLICT(identifier) DO UPDATE SET verified=cap_lead_identifiers.verified OR EXCLUDED.verified', [value, leadId, type, type === 'email' && Boolean(record.email_verification?.status === 'valid')]); }
      }
      for (const event of reconciled.events) await query('INSERT INTO cap_acquisition_events(lead_id,event_type,source,payload) VALUES($1,$2,$3,$4)', [String(event.kept || event.record?.id || event.duplicate?.id || ''), event.type, 'reconciliation', event]);
      return { imported: reconciled.records.length, input_records: (manifest.records || []).length, duplicates_reconciled: reconciled.duplicates, conflicts: reconciled.conflicts.length, high_intent: reconciled.records.filter(highIntent).length, campaign: campaignName };
    },
    async listLeads() { const result = await query('SELECT record FROM cap_leads ORDER BY lead_id'); return result.rows.map((row) => row.record); },
    async saveLead(lead) { const id = strongIdentity(lead); const leadId = String(lead.uid || lead.id); await query(`INSERT INTO cap_leads(lead_id,business,phone,normalized_domain,normalized_email,normalized_phone,company_location_key,internet_presence,high_intent,record) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(lead_id) DO UPDATE SET business=EXCLUDED.business,phone=COALESCE(EXCLUDED.phone,cap_leads.phone),normalized_domain=COALESCE(EXCLUDED.normalized_domain,cap_leads.normalized_domain),normalized_email=COALESCE(EXCLUDED.normalized_email,cap_leads.normalized_email),normalized_phone=COALESCE(EXCLUDED.normalized_phone,cap_leads.normalized_phone),company_location_key=EXCLUDED.company_location_key,internet_presence=COALESCE(EXCLUDED.internet_presence,cap_leads.internet_presence),high_intent=EXCLUDED.high_intent,record=EXCLUDED.record,updated_at=now()`, [leadId, lead.name || lead.business || 'Unknown', lead.phone || null, id.domain || null, id.email || null, id.phone || null, id.companyLocation, lead.internet_presence || lead.internetPresence || null, highIntent(lead), lead]); for (const value of identifiers(lead)) { const [type] = value.split(':'); await query('INSERT INTO cap_lead_identifiers(identifier,lead_id,identifier_type,verified) VALUES($1,$2,$3,$4) ON CONFLICT(identifier) DO UPDATE SET verified=cap_lead_identifiers.verified OR EXCLUDED.verified', [value, leadId, type, type === 'email' && lead.email_verification?.status === 'valid']); } },
    async getLead(leadId) { const result = await query('SELECT record FROM cap_leads WHERE lead_id=$1', [String(leadId)]); return result.rows[0]?.record || null; },
    async enqueue(job) { await query('INSERT INTO cap_queue_jobs(id,lead_id,type,provider,payload,status,attempts) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT (id) DO NOTHING', [job.id, String(job.lead_id), job.type, job.provider || null, job, job.status || 'QUEUED', job.attempts || 0]); },
    async listQueue() { const result = await query("SELECT payload || jsonb_build_object('status',status,'attempts',attempts,'last_error',last_error,'created_at',created_at,'updated_at',updated_at) AS job FROM cap_queue_jobs ORDER BY created_at DESC LIMIT 500"); return result.rows.map((row) => row.job); },
    async claimNext() { const client = await pool.connect(); try { await client.query('BEGIN'); const result = await client.query(`UPDATE cap_queue_jobs SET status='PROCESSING',locked_at=now(),updated_at=now(),attempts=attempts+1 WHERE id=(SELECT id FROM cap_queue_jobs WHERE status IN ('QUEUED','RETRY') AND available_at<=now() ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 1) RETURNING *`); await client.query('COMMIT'); return result.rows[0] || null; } catch (e) { await client.query('ROLLBACK'); throw e; } finally { client.release(); } },
    async completeJob(id, status, error = null) { await query('UPDATE cap_queue_jobs SET status=$2,last_error=$3,completed_at=CASE WHEN $2=\'COMPLETED\' THEN now() ELSE completed_at END,updated_at=now() WHERE id=$1', [id, status, error]); },
    async reserveEmail({ leadId, campaignId, idempotencyKey, dailyLimit, dateBucket = new Date().toISOString().slice(0, 10) }) { const client = await pool.connect(); try { await client.query('BEGIN'); await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1, 0))', [`EMAIL:${campaignId}:${dateBucket}`]); const existing = await client.query('SELECT * FROM cap_outreach_ledger WHERE idempotency_key=$1 FOR UPDATE', [idempotencyKey]); if (existing.rows[0]) { await client.query('COMMIT'); return existing.rows[0]; } const count = await client.query("SELECT count(*)::int AS count FROM cap_outreach_ledger WHERE date_bucket=$1 AND channel='EMAIL' AND final_state IN ('RESERVED','QUEUED','ACCEPTED','DELIVERED')", [dateBucket]); if (count.rows[0].count >= dailyLimit) { await client.query('ROLLBACK'); throw new Error('daily_email_outreach_limit_reached'); } const result = await client.query("INSERT INTO cap_outreach_ledger(lead_id,campaign_id,channel,date_bucket,idempotency_key,final_state) VALUES($1,$2,'EMAIL',$3,$4,'RESERVED') ON CONFLICT(lead_id,campaign_id,channel,date_bucket) DO NOTHING RETURNING *", [String(leadId), String(campaignId), dateBucket, idempotencyKey]); await client.query('COMMIT'); if (!result.rows[0]) throw new Error('daily_outreach_already_reserved'); return result.rows[0]; } catch (e) { try { await client.query('ROLLBACK'); } catch {} throw e; } finally { client.release(); } },
    async markEmailAccepted({ idempotencyKey, providerMessageId, acceptedAt }) { await query("UPDATE cap_outreach_ledger SET provider_message_id=$2,provider_accepted_at=$3,final_state='ACCEPTED' WHERE idempotency_key=$1", [idempotencyKey, providerMessageId, acceptedAt]); },
    async markEmailSuppressed(idempotencyKey) { await query("UPDATE cap_outreach_ledger SET final_state='SUPPRESSED' WHERE idempotency_key=$1", [idempotencyKey]); },
    async recordSuppression(kind, value, reason, source) { await query('INSERT INTO cap_suppressions(kind,value,reason,source) VALUES($1,$2,$3,$4) ON CONFLICT(kind,value) DO UPDATE SET reason=EXCLUDED.reason,source=EXCLUDED.source', [kind, value, reason, source]); },
    async isSuppressed(lead) { const values = [['email', normalizeEmail(lead.email)], ['phone', normalizePhone(lead.phone)]].filter(([, v]) => v); if (!values.length) return false; const result = await query('SELECT 1 FROM cap_suppressions WHERE (kind,value)=ANY($1::text[][]) LIMIT 1', [values]); return Boolean(result.rows[0]); },
    async recordAcquisitionRun(metrics) { await query('INSERT INTO cap_acquisition_runs(date_bucket,source,discovered,duplicates,new_unique,no_web_presence,social_only,weak_website,domain_prospects,enriched,verified_email,phone_only,rejected) VALUES(current_date,$1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)', [metrics.source || 'acquisition', metrics.discovered || 0, metrics.duplicates || 0, metrics.new_unique || 0, metrics.no_web_presence || 0, metrics.social_only || 0, metrics.weak_website || 0, metrics.domain_prospects || 0, metrics.enriched || 0, metrics.verified_email || 0, metrics.phone_only || 0, metrics.rejected || 0]); },
    async listAcquisitionRuns(limit = 50) { const result = await query('SELECT id,date_bucket,source,discovered,duplicates,new_unique,no_web_presence,social_only,weak_website,domain_prospects,enriched,verified_email,phone_only,rejected,created_at FROM cap_acquisition_runs ORDER BY created_at DESC LIMIT $1', [Math.min(Math.max(Number(limit)||50,1),200)]); return result.rows; },
    async recordAdminEvent({ actor='system', event_type, entity_type=null, entity_id=null, payload={} }) { await query('INSERT INTO cap_admin_events(actor,event_type,entity_type,entity_id,payload) VALUES($1,$2,$3,$4,$5)', [actor,event_type,entity_type,entity_id,payload]); },
    async listAdminEvents(limit = 200) { const result = await query('SELECT id,actor,event_type,entity_type,entity_id,payload,occurred_at FROM cap_admin_events ORDER BY occurred_at DESC LIMIT $1', [Math.min(Math.max(Number(limit)||200,1),500)]); return result.rows; },
    async saveEvent(event) { const entityId = /^[0-9a-f-]{36}$/i.test(String(event.entity_id || '')) ? event.entity_id : null; await query('INSERT INTO events(event_type,entity_type,entity_id,payload) VALUES($1,$2,$3,$4)', [event.type || event.event_type, event.entity_type || 'lead', entityId, event.payload || {}]); },
    async close() { await pool.end(); },
  };
}
export function newJobId() { return randomUUID(); }
