#!/usr/bin/env bash
set -euo pipefail
REGION=${AWS_REGION:-eu-north-1}; ACCOUNT=${AWS_ACCOUNT_ID:-795804715712}; REPO=aureum-cap-v01-api; CLUSTER=aureum-cap-v01-api; SERVICE=aureum-cap-v01-api; WORKER_SERVICE=aureum-cap-v01-worker; IMAGE="$ACCOUNT.dkr.ecr.$REGION.amazonaws.com/$REPO:production"; RUNTIME_SECRET_NAME=aureum-cap-v01-api-runtime; WORKDIR="${PWD}"
RDS_SECRET_NAME=$(aws secretsmanager list-secrets --region "$REGION" --query 'SecretList[?starts_with(Name, `rds!`)].Name | [0]' --output text); [[ "$RDS_SECRET_NAME" != "None" && -n "$RDS_SECRET_NAME" ]] || { echo 'RDS managed secret not found.' >&2; exit 1; }
RDS_JSON=$(aws secretsmanager get-secret-value --region "$REGION" --secret-id "$RDS_SECRET_NAME" --query SecretString --output text); DB_USER=$(aws rds describe-db-instances --region "$REGION" --db-instance-identifier aureum-cap-v01-db --query 'DBInstances[0].MasterUsername' --output text); DB_HOST=$(aws rds describe-db-instances --region "$REGION" --db-instance-identifier aureum-cap-v01-db --query 'DBInstances[0].Endpoint.Address' --output text); DB_PORT=$(aws rds describe-db-instances --region "$REGION" --db-instance-identifier aureum-cap-v01-db --query 'DBInstances[0].Endpoint.Port' --output text); DB_PASS=$(jq -r 'if type=="object" then (to_entries[] | select(.key|ascii_downcase|test("pass")) | .value) else . end' <<<"$RDS_JSON" | head -n1); DATABASE_URL="postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/postgres"
EXISTING='{}'; if aws secretsmanager describe-secret --region "$REGION" --secret-id "$RUNTIME_SECRET_NAME" >/dev/null 2>&1; then EXISTING=$(aws secretsmanager get-secret-value --region "$REGION" --secret-id "$RUNTIME_SECRET_NAME" --query SecretString --output text); fi; jq -e . >/dev/null 2>&1 <<<"$EXISTING" || EXISTING='{}'
RUNTIME_JSON=$(jq -n --argjson e "$EXISTING" --arg db "$DATABASE_URL" --arg email "${CAP_ADMIN_EMAIL:-}" --arg pass "${CAP_ADMIN_PASSWORD:-}" '($e//{}) | .DATABASE_URL=$db | if $email != "" then .CAP_ADMIN_EMAIL=$email else . end | if $pass != "" then .CAP_ADMIN_PASSWORD=$pass else . end | .OPENAI_MODEL=(.OPENAI_MODEL//"gpt-5.6-luna") | .CAP_DAILY_ACQUISITION_TARGET=(.CAP_DAILY_ACQUISITION_TARGET//"1000") | .CAP_DAILY_EMAIL_OUTREACH_LIMIT=(.CAP_DAILY_EMAIL_OUTREACH_LIMIT//"250") | .CAP_ALLOWED_ORIGIN="https://aureum-cap-v0-1.vercel.app" | .FRONTEND_ORIGIN="https://aureum-cap-v0-1.vercel.app" | .PUBLIC_API_BASE_URL="https://api.cactusdigitalmedia.ng" | .AWS_REGION="eu-north-1" | .CAP_S3_BUCKET=(.CAP_S3_BUCKET//"aureum-cap-v01-assets-795804715712") | .CAP_SQS_QUEUE_URL=(.CAP_SQS_QUEUE_URL//"https://sqs.eu-north-1.amazonaws.com/795804715712/aureum-cap-v01-lead-processing") | .CAP_SQS_DLQ_URL=(.CAP_SQS_DLQ_URL//"https://sqs.eu-north-1.amazonaws.com/795804715712/aureum-cap-v01-lead-processing-dlq") | .SES_FROM_EMAIL=(.SES_FROM_EMAIL//"aureum.cap@cactusdigitalmedia.ng") | .SMS_STATUS_CALLBACK_URL="https://api.cactusdigitalmedia.ng/api/v1/webhooks/sms/status" | .NODE_ENV="production"')
if aws secretsmanager describe-secret --region "$REGION" --secret-id "$RUNTIME_SECRET_NAME" >/dev/null 2>&1; then aws secretsmanager put-secret-value --region "$REGION" --secret-id "$RUNTIME_SECRET_NAME" --secret-string "$RUNTIME_JSON" >/dev/null; else aws secretsmanager create-secret --region "$REGION" --name "$RUNTIME_SECRET_NAME" --secret-string "$RUNTIME_JSON" >/dev/null; fi
RUNTIME_ARN=$(aws secretsmanager describe-secret --region "$REGION" --secret-id "$RUNTIME_SECRET_NAME" --query ARN --output text); aws ecr get-login-password --region "$REGION" | docker login --username AWS --password-stdin "$ACCOUNT.dkr.ecr.$REGION.amazonaws.com"; docker build -t "$IMAGE" "$WORKDIR"; docker push "$IMAGE"
SECRET_NAMES='DATABASE_URL CAP_ADMIN_EMAIL CAP_ADMIN_PASSWORD OPENAI_API_KEY OPENAI_MODEL HUNTER_API_KEY CAP_DAILY_ACQUISITION_TARGET CAP_DAILY_EMAIL_OUTREACH_LIMIT CAP_EMAIL_SEND_ENABLED CAP_SMS_SEND_ENABLED CAP_WHATSAPP_SEND_ENABLED CAP_S3_BUCKET CAP_SQS_QUEUE_URL CAP_SQS_DLQ_URL SES_FROM_EMAIL TWILIO_ACCOUNT_SID TWILIO_AUTH_TOKEN TWILIO_FROM_NUMBER TWILIO_MESSAGING_SERVICE_SID SMS_STATUS_CALLBACK_URL AWS_REGION FRONTEND_ORIGIN PUBLIC_API_BASE_URL NODE_ENV'
SECRETS_JSON='['; for name in $SECRET_NAMES; do SECRETS_JSON+="{\"name\":\"$name\",\"valueFrom\":\"$RUNTIME_ARN:$name::\"},"; done; SECRETS_JSON="${SECRETS_JSON%,}]"
make_task() { local family=$1 container=$2 command=$3; jq -n --arg family "$family" --arg image "$IMAGE" --arg name "$container" --argjson secrets "$SECRETS_JSON" --arg command "$command" '{family:$family,networkMode:"awsvpc",requiresCompatibilities:["FARGATE"],cpu:"256",memory:"512",executionRoleArn:"arn:aws:iam::795804715712:role/aureum-cap-v01-ecs-execution-role",taskRoleArn:"arn:aws:iam::795804715712:role/aureum-cap-v01-api-task-role",containerDefinitions:[{name:$name,image:$image,essential:true,secrets:$secrets,entryPoint:["sh","-c"],command:[$command],logConfiguration:{logDriver:"awslogs",options:{"awslogs-group":("/ecs/"+$family),"awslogs-region":"eu-north-1","awslogs-stream-prefix":$name}}}}]}'; }
# Deploy API task with the API entry point; worker gets the same secret references and a distinct command.
make_task aureum-cap-v01-api api 'node server/index.mjs' >/tmp/cap-api-task.json; jq '.containerDefinitions[0].portMappings=[{containerPort:8787,protocol:"tcp"}]' /tmp/cap-api-task.json >/tmp/cap-api-task.fixed && mv /tmp/cap-api-task.fixed /tmp/cap-api-task.json; make_task aureum-cap-v01-worker worker 'node workers/sqs-worker.mjs' >/tmp/cap-worker-task.json
aws logs create-log-group --region "$REGION" --log-group-name /ecs/aureum-cap-v01-api 2>/dev/null || true; aws logs create-log-group --region "$REGION" --log-group-name /ecs/aureum-cap-v01-worker 2>/dev/null || true
API_TASK=$(aws ecs register-task-definition --region "$REGION" --cli-input-json file:///tmp/cap-api-task.json --query 'taskDefinition.taskDefinitionArn' --output text); WORKER_TASK=$(aws ecs register-task-definition --region "$REGION" --cli-input-json file:///tmp/cap-worker-task.json --query 'taskDefinition.taskDefinitionArn' --output text)
aws ecs update-service --region "$REGION" --cluster "$CLUSTER" --service "$SERVICE" --task-definition "$API_TASK" --force-new-deployment >/dev/null
if aws ecs describe-services --region "$REGION" --cluster "$CLUSTER" --services "$WORKER_SERVICE" --query 'services[0].serviceName' --output text 2>/dev/null | grep -qx "$WORKER_SERVICE"; then aws ecs update-service --region "$REGION" --cluster "$CLUSTER" --service "$WORKER_SERVICE" --task-definition "$WORKER_TASK" --desired-count 1 --force-new-deployment >/dev/null; else echo "Worker service $WORKER_SERVICE does not exist; create it with the existing queue networking/IAM configuration before enabling EMAIL_SEND jobs." >&2; fi
aws ecs wait services-stable --region "$REGION" --cluster "$CLUSTER" --services "$SERVICE"; aws ecs describe-services --region "$REGION" --cluster "$CLUSTER" --services "$SERVICE" --query 'services[0].{status:status,running:runningCount,desired:desiredCount,taskDefinition:taskDefinition}' --output json; curl -fsS --max-time 20 https://api.cactusdigitalmedia.ng/health; echo
