import { SQSClient, ReceiveMessageCommand, DeleteMessageCommand, ChangeMessageVisibilityCommand, SendMessageCommand } from '@aws-sdk/client-sqs';
import { createRepository } from '../db/repository.mjs';
import { sendTwilioSms, sendTermiiSms } from '../server/sms.mjs';
import { sendSESEmail, hunterDomainSearch, hunterEmailFinder, hunterEmailVerifier, openaiResponses } from '../server/services.mjs';
const queueUrl = process.env.CAP_SQS_QUEUE_URL; const dlqUrl = process.env.CAP_SQS_DLQ_URL; const repository = createRepository();
if (!queueUrl) throw new Error('CAP_SQS_QUEUE_URL is required'); if (!repository) throw new Error('DATABASE_URL is required');
const sqs = new SQSClient({ region: process.env.AWS_REGION || 'eu-north-1' }); const maxAttempts = Number(process.env.CAP_WORKER_MAX_ATTEMPTS || 3);
const now = () => new Date().toISOString();
async function loadLead(job) { const lead = await repository.getLead(job.lead_id); if (!lead) throw new Error(`lead_not_found:${job.lead_id}`); return lead; }
async function processMessage(message) {
  const job = JSON.parse(message.Body); if (!job.type) throw new Error('job_type_required'); const lead = await loadLead(job);
  if (job.type === 'SMS_SEND') { if (process.env.CAP_SMS_SEND_ENABLED !== 'true') throw new Error('CAP_SMS_SEND_ENABLED is false'); const result = job.provider === 'twilio' ? await sendTwilioSms({ to: job.to, body: job.body, statusCallback: process.env.SMS_STATUS_CALLBACK_URL }) : await sendTermiiSms({ to: job.to, body: job.body }); lead.sms_provider_id = result.provider_id; lead.sms_status = result.status; lead.sms_sent_at = now(); lead.lifecycle_stage = 'SENT'; await repository.saveLead(lead); await repository.saveEvent({ type: 'sms.provider.accepted', entity_type: 'lead', payload: { lead_id: job.lead_id, provider: result.provider, provider_id: result.provider_id, status: result.status } }); }
  else if (job.type === 'EMAIL_SEND') { const result = await sendSESEmail({ to: job.to, subject: job.subject, body: job.body, campaignId: job.campaign_id, leadId: job.lead_id }); lead.email_provider_id = result.provider_id; lead.email_status = 'ACCEPTED'; lead.email_sent_at = result.accepted_at; lead.email_sent_date = result.accepted_at.slice(0, 10); lead.lifecycle_stage = 'EMAIL_ACCEPTED'; await repository.saveLead(lead); await repository.markEmailAccepted({ idempotencyKey: job.idempotency_key, providerMessageId: result.provider_id, acceptedAt: result.accepted_at }); await repository.saveEvent({ type: 'email.provider.accepted', entity_type: 'lead', payload: { lead_id: job.lead_id, provider: result.provider, provider_id: result.provider_id, status: result.status, accepted_at: result.accepted_at } }); }
  else if (job.type === 'LEAD_ENRICH') { const domain = job.domain || lead.website || lead.domain; if (domain) { const result = await hunterDomainSearch(domain); lead.hunter_enrichment = { provider: 'hunter', domain, data: result.data, source: 'hunter-domain-search', received_at: now() }; const first = result.data?.emails?.find((e) => e.value); if (first && !lead.email) { lead.email = first.value; lead.email_confidence = first.confidence; lead.email_source = 'hunter'; } } else { lead.hunter_enrichment = { provider: 'hunter', skipped: true, reason: 'no_domain', received_at: now() }; } lead.enriched_at = now(); lead.lifecycle_stage = 'ENRICHED'; await repository.saveLead(lead); await repository.saveEvent({ type: 'hunter.enriched', entity_type: 'lead', payload: { lead_id: job.lead_id, data: lead.hunter_enrichment } }); }
  else if (job.type === 'EMAIL_VERIFY') { if (!job.email && !lead.email) throw new Error('email_required'); const email = job.email || lead.email; const result = await hunterEmailVerifier(email); lead.email_verification = { provider: 'hunter', email, result: result.data, status: result.data?.status || result.data?.result || 'unknown', verified_at: now() }; lead.email_status = lead.email_verification.status === 'valid' ? 'VERIFIED' : 'UNVERIFIED'; await repository.saveLead(lead); await repository.saveEvent({ type: 'hunter.verified', entity_type: 'lead', payload: { lead_id: job.lead_id, email, data: result.data } }); }
  else if (job.type === 'OPENAI_QUALIFY') { const result = await openaiResponses(job.input || `Qualify ${lead.name} for website development. Internet presence: ${lead.internet_presence || 'unknown'}.`, job.schema || { name: 'qualification', schema: { type: 'object', properties: { score: { type: 'number' }, high_intent: { type: 'boolean' }, rationale: { type: 'string' }, opportunity: { type: 'string' } }, required: ['score', 'high_intent', 'rationale', 'opportunity'], additionalProperties: false } }); const parsed = JSON.parse(result.output_text); lead.openai_qualification = { ...parsed, model: result.model, request_id: result.id, usage: result.usage, qualified_at: now() }; lead.score = { ...(lead.score || {}), total: parsed.score, rationale: parsed.rationale, source: 'openai', model: result.model }; lead.high_intent = Boolean(parsed.high_intent); lead.lifecycle_stage = 'QUALIFIED'; await repository.saveLead(lead); await repository.saveEvent({ type: 'openai.qualified', entity_type: 'lead', payload: { lead_id: job.lead_id, qualification: lead.openai_qualification } }); }
  else throw new Error(`unsupported_job_type:${job.type}`);
  return job;
}
async function runOnce() { const response = await sqs.send(new ReceiveMessageCommand({ QueueUrl: queueUrl, MaxNumberOfMessages: 10, WaitTimeSeconds: 20, VisibilityTimeout: 120, AttributeNames: ['ApproximateReceiveCount'] })); for (const message of response.Messages || []) { const attempts = Number(message.Attributes?.ApproximateReceiveCount || 1); try { const processed = await processMessage(message); await repository.completeJob(processed.id, 'COMPLETED'); await sqs.send(new DeleteMessageCommand({ QueueUrl: queueUrl, ReceiptHandle: message.ReceiptHandle })); } catch (error) { console.error('JOB_FAILED', JSON.stringify({ error: error.message, attempts, message_id: message.MessageId })); if (attempts >= maxAttempts && dlqUrl) { await repository.completeJob(JSON.parse(message.Body).id, 'DLQ', error.message); await sqs.send(new SendMessageCommand({ QueueUrl: dlqUrl, MessageBody: message.Body })); await sqs.send(new DeleteMessageCommand({ QueueUrl: queueUrl, ReceiptHandle: message.ReceiptHandle })); } else { await repository.completeJob(JSON.parse(message.Body).id, 'RETRY', error.message); await sqs.send(new ChangeMessageVisibilityCommand({ QueueUrl: queueUrl, ReceiptHandle: message.ReceiptHandle, VisibilityTimeout: Math.min(900, 2 ** attempts * 30) })); } } } }
console.log('CAP SQS worker started'); while (true) await runOnce();
